### ISSUE TITLE
Problem running bebop_without_controller.launch

### ISSUE THREAD

**Issue by ss26** [gsilano/BebopS#8]
I'm using Ubuntu 16.04 with ROS Kinetic. Gazebo version 7 was installed automatically with my ROS installation. I had no problem installing the BebopS simulator. However, it did say '6 packages succeeded with warnings' during the build. I didn't pay much heed to it since it succeeded. Now coming to the problem, I tried running the command 

`roslaunch bebop_simulator bebop_without_controller.launch`

but it shows me this error: 

![image](https://user-images.githubusercontent.com/27211131/71748044-68b73d00-2e97-11ea-9e54-e42017e5f544.png)

Please help.

**Comment by gsilano** [comment]
HI @valarsundarlis!! First of all, thanks for your interest in BebopS. As for your question, don't worry about the warnings. The package uses an older version of the Eigen package (it is now Eigen3) and, for this reason, warnings are generated saying that the library should be updated with the new release.

I fixed the error (there was a typo), it should now be ok. Please let me know if there are any other problems. In the meantime, I close the issue.

For the next time, try to copy and paste the text shown on the terminal line instead of attaching the image. In this way it easier to understand what went wrong.
